# Generated by Django 3.1.4 on 2020-12-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number_first', models.CharField(max_length=50)),
                ('phone_number_two', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
